# docker-compose.yml
version: '3.1'
services:
  db:
    image: 'sqlite'
    volumes:
      - './data:/data' 
    command: 'sqlite3 /data/mydatabase.db'
  api:
    build: .
    depends_on:
      - db
    ports:
      - '8080:8080'
